# Generated by Django 6.0.5 on 2026-07-21 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryid', models.AutoField(db_column='CountryID', primary_key=True, serialize=False)),
                ('countryname', models.CharField(db_column='CountryName', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customsclearance',
            fields=[
                ('clearanceid', models.AutoField(db_column='ClearanceID', primary_key=True, serialize=False)),
                ('inspectiondate', models.DateTimeField(db_column='InspectionDate')),
                ('clearancestatus', models.CharField(db_column='ClearanceStatus', max_length=20)),
                ('documentref', models.CharField(blank=True, db_column='DocumentRef', max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
            ],
            options={
                'db_table': 'customsclearance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('dependentid', models.AutoField(db_column='DependentID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
            ],
            options={
                'db_table': 'dependent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Freightshipment',
            fields=[
                ('shipmentid', models.AutoField(db_column='ShipmentID', primary_key=True, serialize=False)),
                ('shippername', models.CharField(db_column='ShipperName', max_length=100)),
                ('cargotype', models.CharField(db_column='CargoType', max_length=50)),
                ('weightkg', models.DecimalField(db_column='WeightKG', decimal_places=2, max_digits=10)),
                ('containercount', models.IntegerField(db_column='ContainerCount')),
                ('currentstatus', models.CharField(db_column='CurrentStatus', max_length=30)),
            ],
            options={
                'db_table': 'freightshipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loyaltyclass',
            fields=[
                ('classid', models.AutoField(db_column='ClassID', primary_key=True, serialize=False)),
                ('classname', models.CharField(db_column='ClassName', max_length=20, unique=True)),
                ('milesrequired', models.IntegerField(db_column='MilesRequired')),
                ('discountpercentage', models.DecimalField(db_column='DiscountPercentage', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'loyaltyclass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('luggage_id', models.AutoField(db_column='LuggageID', primary_key=True, serialize=False)),
                ('weight_kg', models.DecimalField(db_column='WeightKG', decimal_places=2, max_digits=5)),
                ('bag_count', models.IntegerField(db_column='BagCount', default=1)),
            ],
            options={
                'db_table': 'Luggage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenancerecord',
            fields=[
                ('recordid', models.AutoField(db_column='RecordID', primary_key=True, serialize=False)),
                ('targettype', models.CharField(db_column='TargetType', max_length=20)),
                ('maintenancedate', models.DateField(db_column='MaintenanceDate')),
                ('maintenancestatus', models.CharField(db_column='MaintenanceStatus', max_length=20)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
            ],
            options={
                'db_table': 'maintenancerecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passengerid', models.AutoField(db_column='PassengerID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('totalmiles', models.IntegerField(blank=True, db_column='TotalMiles', null=True)),
            ],
            options={
                'db_table': 'passenger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationid', models.AutoField(db_column='ReservationID', primary_key=True, serialize=False)),
                ('traveldate', models.DateField(db_column='TravelDate')),
                ('coachtype', models.CharField(db_column='CoachType', max_length=20)),
                ('seatnumber', models.CharField(db_column='SeatNumber', max_length=10)),
                ('ticketprice', models.DecimalField(db_column='TicketPrice', decimal_places=2, max_digits=10)),
                ('paymentstatus', models.CharField(db_column='PaymentStatus', max_length=20)),
                ('ticketstatus', models.CharField(db_column='TicketStatus', max_length=20)),
                ('expiry_date', models.DateTimeField(blank=True, db_column='ExpiryDate', null=True)),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensorreading',
            fields=[
                ('readingid', models.AutoField(db_column='ReadingID', primary_key=True, serialize=False)),
                ('readingtype', models.CharField(db_column='ReadingType', max_length=50)),
                ('readingvalue', models.DecimalField(db_column='ReadingValue', decimal_places=2, max_digits=10)),
                ('readingtime', models.DateTimeField(db_column='ReadingTime')),
                ('isnormal', models.IntegerField(blank=True, db_column='IsNormal', null=True)),
            ],
            options={
                'db_table': 'sensorreading',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.AutoField(db_column='StaffID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('jobrole', models.CharField(db_column='JobRole', max_length=50)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staffassignment',
            fields=[
                ('assignmentid', models.AutoField(db_column='AssignmentID', primary_key=True, serialize=False)),
                ('assignmentdate', models.DateField(db_column='AssignmentDate')),
                ('roleontrain', models.CharField(blank=True, db_column='RoleOnTrain', max_length=50, null=True)),
            ],
            options={
                'db_table': 'staffassignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationid', models.AutoField(db_column='StationID', primary_key=True, serialize=False)),
                ('stationname', models.CharField(db_column='StationName', max_length=150)),
                ('stationtype', models.CharField(db_column='StationType', max_length=50)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tracksegment',
            fields=[
                ('trackid', models.AutoField(db_column='TrackID', primary_key=True, serialize=False)),
                ('distancekm', models.DecimalField(db_column='DistanceKM', decimal_places=2, max_digits=6)),
                ('iselectrified', models.IntegerField(blank=True, db_column='IsElectrified', null=True)),
                ('trackstatus', models.CharField(db_column='TrackStatus', max_length=20)),
            ],
            options={
                'db_table': 'tracksegment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('trainid', models.CharField(db_column='TrainID', max_length=20, primary_key=True, serialize=False)),
                ('trainname', models.CharField(db_column='TrainName', max_length=100)),
                ('traintype', models.CharField(db_column='TrainType', max_length=50)),
                ('maxpassengerspeed', models.IntegerField(blank=True, db_column='MaxPassengerSpeed', null=True)),
                ('maxfreightspeed', models.IntegerField(blank=True, db_column='MaxFreightSpeed', null=True)),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trainschedule',
            fields=[
                ('scheduleid', models.AutoField(db_column='ScheduleID', primary_key=True, serialize=False)),
                ('stoporder', models.IntegerField(db_column='StopOrder')),
                ('arrivaltime', models.DateTimeField(blank=True, db_column='ArrivalTime', null=True)),
                ('departuretime', models.DateTimeField(blank=True, db_column='DepartureTime', null=True)),
            ],
            options={
                'db_table': 'trainschedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Waitinglist',
            fields=[
                ('waitlistid', models.AutoField(db_column='WaitlistID', primary_key=True, serialize=False)),
                ('traveldate', models.DateField(db_column='TravelDate')),
            ],
            options={
                'db_table': 'waitinglist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('passenger', models.OneToOneField(blank=True, db_column='PassengerID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='railway.passenger')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
